# Docs for Azure Static Web Apps Deploy action: https://github.com/Azure/static-web-apps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy React app to Azure Static Web App - aquawatch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          cd converter-frontend
          npm install
          npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: converter-frontend/dist

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: converter-frontend/dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'converter-frontend'
          output_location: 'dist'
